### ISSUE TITLE
[报告问题] 你遇到的问题

### ISSUE THREAD

**Issue by xiaohao8** [abnerwei/hexo-url-submission#10]
请问花括号是去掉还是保留?格式能说清楚一下吗。没看懂。
麻烦指出我的仓库配置的问题

**Comment by abnerwei** [comment]
可以贴出来一起看一下

**Comment by abnerwei** [comment]
> 请问花括号是去掉还是保留?格式能说清楚一下吗。没看懂。 麻烦指出我的仓库配置的问题

可以贴出来一起看一下

**Comment by xiaohao8** [comment]
![Screenshot_20230510-221946_EDIT_1683728417811](http://img.202271.xyz:57549/i/2023/05/10/10q2099.png)

**Comment by abnerwei** [comment]
> ![Screenshot_20230510-221946_EDIT_1683728417811](https://camo.githubusercontent.com/c0b8326bd3bfe12369f18bb113dc148277398c75d8674562144684b1b5e6620a/687474703a2f2f696d672e3230323237312e78797a3a35373534392f692f323032332f30352f31302f313071323039392e706e67)

channels后保持空白，其实下面的配置是正确的

```yaml
channels:
    baidu:
        token: ""
        count: 0
   xxxx
```

像上面这样，去掉就好
