### ISSUE TITLE
部署时候出现url_submission: No matching pages found!

### ISSUE THREAD

**Issue by KHTdhl** [abnerwei/hexo-url-submission#11]
INFO  url_submission: Start generating url list...
INFO  url_submission: No matching pages found!
安装插件，在生成页面的时候，会有这样的info。
我的txt文件和xml文件都已经有相关的路径输入（文件也可以正常提交）。这是插件准备完善，自动生成没有做的部分吗？

**Comment by abnerwei** [comment]
可以检查下`submit_url.txt内有没有生成博文链接

**Comment by KHTdhl** [comment]
prefix: ['/post', '/wiki'] # URL prefix
   ignore: ["/post/a*", "/post/a?c"] # URL addresses that do not need to be submitted (wildcards are supported)
   count: 10 # Submit limit
   urls_path: 'sitemap.txt' # URL list file path
   sitemap: 'baidusitemap.xml' # Sitemap path(e.g. the url is like this https://abnerwei.com/baidusitemap.xml, you can fill in `baidusitemap.xml`)


这个是我的文件配置部分，我的 urls_path: 'sitemap.txt' ，这个文件是存在的，这个info我不太明白，我在我的文件夹中找不到submit_url.txt这个文件

**Comment by abnerwei** [comment]
> prefix: ['/post', '/wiki'] # URL prefix ignore: ["/post/a*", "/post/a?c"] # URL addresses that do not need to be submitted (wildcards are supported) count: 10 # Submit limit urls_path: 'sitemap.txt' # URL list file path sitemap: 'baidusitemap.xml' # Sitemap path(e.g. the url is like this https://abnerwei.com/baidusitemap.xml, you can fill in `baidusitemap.xml`)
> 
> 这个是我的文件配置部分，我的 urls_path: 'sitemap.txt' ，这个文件是存在的，这个info我不太明白，我在我的文件夹中找不到submit_url.txt这个文件

这个上面的`prefix`和`ignore`需要改一下，应该是这个组合下，没有匹配的

**Comment by KHTdhl** [comment]
prefix: ['/post', '/wiki'] # URL prefix
ignore: ["/post/a*", "/post/a?c"] # URL addresses that do not need to be submitted (wildcards are supported)
这两个选项我已经在配置文件删除了，执行命令依旧提示
INFO url_submission: Start generating url list...
INFO url_submission: No matching pages found!

**Comment by abnerwei** [comment]
Cannot reproduce, temporarily closed, continue to follow.

**Comment by ousugo** [comment]
> INFO url_submission: Start generating url list... INFO url_submission: No matching pages found! 安装插件，在生成页面的时候，会有这样的info。 我的txt文件和xml文件都已经有相关的路径输入（文件也可以正常提交）。这是插件准备完善，自动生成没有做的部分吗？

出现这个情况，可能的原因是在 hexo _config.yml 配置文件中， `url_submission` 的 `type` 属性保持为默认的 `latest`，在这个选项下， `submit_url.txt` 这个文件是只会在有当天更新的页面才会生成，也就是说如果你最新一篇文章的更改日期不是当天，就会出现 `No matching pages found` 的提示，同样 `submit_url.txt` 文件也直接就不会生成，
