### ISSUE TITLE
[建议] Wiki好像404了欸

### ISSUE THREAD

**Issue by yqs112358** [abnerwei/hexo-url-submission#16]
## 建议

如题，Wiki链接好像404了。希望可以补全一下README中的信息，比如具体如何`use environment variables in your local or CI/CD tools to safely store tokens`，用哪些key名？

**Comment by abnerwei** [comment]
> ## 建议
> 如题，Wiki链接好像404了。希望可以补全一下README中的信息，比如具体如何`use environment variables in your local or CI/CD tools to safely store tokens`，用哪些key名？

感谢建议，我待会儿就去详细补充下这块文档。

**Comment by yqs112358** [comment]
刚发现webarchive好像有：https://web.archive.org/web/20230602195420/https://abnerwei.com/wiki/hexo/url-submission/ 🥰
