### ISSUE TITLE
提交到谷歌：Request failed with status code 400

### ISSUE THREAD

**Issue by ousugo** [abnerwei/hexo-url-submission#6]
## Information 信息
![image](https://user-images.githubusercontent.com/43401755/187335274-ca61ab38-9ec0-4f4c-84e1-b0177182d64f.png)

**Version/版本:**
hexo-url-submission@1.0.8

**Platform/操作系统:**
Windows

**npm版本:**
8.18.0

**hexo版本:**
hexo@5.4.2

**科学上网方式:**
Clash For Windows，端口1082

## Expected behaviour 预期行为
**答：**
成功提交到谷歌

## Actual behaviour 实际行为

**答：**
![image](https://user-images.githubusercontent.com/43401755/187335104-b2b7f925-1877-4de7-aa50-64afc6771bef.png)

## Steps to reproduce the behaviour 重现步骤
**答：**
hexo clean && hexo g && hexo d

## Feature Request 功能方面的建议

**答：**

---

**Comment by abnerwei** [comment]
Hi~, I think this problem has been solved in the new version (v1.0.9) .
