### ISSUE TITLE
[建议] 增加排除列表、剩余提交量、独立限额控制等

### ISSUE THREAD

**Issue by du33169** [abnerwei/hexo-url-submission#7]
## 建议

1. 目前只支持通过prefix筛选，但是大部分时候只需要排除少数页面，希望增加排除功能
2. 目前通过count参数配置提交的链接数量，但不同搜索引擎的配额不同，例如百度一天可以提交上千链接，必应在一开始一天只能提交10条，希望能够不同channel独立控制
3. 百度和必应的提交API支持返回当日剩余提交配额，希望能够在输出结果中显示
4. 在`hexo g`命令时，会输出：
```bash
  INFO  url_submission: Submit all matching URLs to the search engine successfully!
```
生成阶段只是生成了链接吧，这里写“成功提交到搜索引擎”的表述是否不太合适？

**Comment by abnerwei** [comment]
> ## 建议
> 1. 目前只支持通过prefix筛选，但是大部分时候只需要排除少数页面，希望增加排除功能
> 2. 目前通过count参数配置提交的链接数量，但不同搜索引擎的配额不同，例如百度一天可以提交上千链接，必应在一开始一天只能提交10条，希望能够不同channel独立控制
> 3. 百度和必应的提交API支持返回当日剩余提交配额，希望能够在输出结果中显示
> 4. 在`hexo g`命令时，会输出：
> 
> ```shell
>   INFO  url_submission: Submit all matching URLs to the search engine successfully!
> ```
> 
> 生成阶段只是生成了链接吧，这里写“成功提交到搜索引擎”的表述是否不太合适？

Brilliant idea!
