### ISSUE TITLE
[报告问题] 提交失败 `Extract url file failed`

### ISSUE THREAD

**Issue by yyhhkya** [abnerwei/hexo-url-submission#8]
![image](https://user-images.githubusercontent.com/87574541/205704628-d7829b6f-0f42-4208-bc9e-cba7ef519b03.png)

提交（`hexo d`）失败

**Comment by yyhhkya** [comment]
![image](https://user-images.githubusercontent.com/87574541/205704849-59e6c3c0-c85f-477d-8a2e-4ef7f3dcb9d2.png)
![image](https://user-images.githubusercontent.com/87574541/205704918-9a5abd6e-dcab-4f6c-9620-6777f510583a.png)
![image](https://user-images.githubusercontent.com/87574541/205704995-b92772f3-f131-42e4-90ed-f6a55ca3275a.png)

**Comment by abnerwei** [comment]
感谢反馈，我来排查下

来自 Abnerwei

**Comment by abnerwei** [comment]
> ![image](https://user-images.githubusercontent.com/87574541/205704628-d7829b6f-0f42-4208-bc9e-cba7ef519b03.png)
> 
> 提交（`hexo d`）失败

从log看，应该是生成url列表文件失败了，可以贴一下详细的log吗？

**Comment by yyhhkya** [comment]
这个问题我已经解决了 原因是因为我以为`urls_path`是自动生成的 我把这个改成已经生成好的链接就可以了 
![image](https://user-images.githubusercontent.com/87574541/206391530-38e0ffb5-28da-40ce-8530-dd64e50bcb59.png)

但是谷歌推送不了 提交提示`Google key file not exist.` 我的json文件就在网站的根目录

**Comment by yyhhkya** [comment]
这个问题我已经解决了 原因是因为我以为urls_path是自动生成的 我把这个改成已经生成好的链接就可以了
![image](https://user-images.githubusercontent.com/87574541/206394138-e354d07e-0e60-4775-b92b-8274f58bcd34.png)

但是谷歌推送不了 提交提示Google key file not exist. 我的json文件就在网站的根目录
![image](https://user-images.githubusercontent.com/87574541/206394186-863c43dc-29f5-453d-9b2c-51ce7df4bd96.png)

**Comment by abnerwei** [comment]
这个应该是google key 参数配置问题，google_key 那里填写 json 文件路径，例如： `./data/google_key.json` 新版本里会加上一些默认值，降低配置成本

**Comment by yyhhkya** [comment]
![image](https://user-images.githubusercontent.com/87574541/206395431-432a72c4-c5e3-447d-b3de-b1d31168d26b.png)
我改成了这样 还是不行

**Comment by yyhhkya** [comment]
一直提示`Google key file not exist.`

**Comment by abnerwei** [comment]
google_key 的 json 文件放在项目根目录，这样没问题

**Comment by yyhhkya** [comment]
我也不知道是怎么回事 但他就提示密钥文件不存在

**Comment by yyhhkya** [comment]
![image](https://user-images.githubusercontent.com/87574541/206398706-921e925c-661c-42d3-ac95-022a78cc43b2.png)

**Comment by abnerwei** [comment]
> ![image](https://user-images.githubusercontent.com/87574541/206398706-921e925c-661c-42d3-ac95-022a78cc43b2.png)

这个配置文件，无需提交到`public`目录，不要暴露出去，放在你的 `hexo` 源文件目录即可。

**Comment by yyhhkya** [comment]
这个文件是就放在`source`文件夹里面就行了吗

**Comment by abnerwei** [comment]
> 这个文件是就放在`source`文件夹里面就行了吗

放到source会打包到public，放在source同级，项目根目录就好

**Comment by yyhhkya** [comment]
![image](https://user-images.githubusercontent.com/87574541/206400138-fd3ba4b4-2825-4678-8522-b61f3f71398f.png)

好的 谢谢 问题已经解决啦~
